copy \faceprog\com\FCP.dpr
copy \faceprog\com\Alarms.pas
copy \faceprog\com\AVSD.pas
copy \faceprog\com\Backup.pas
copy \faceprog\com\Bitmaps.pas
copy \faceprog\com\CalibAut.pas
copy \faceprog\com\CalibMan.pas
copy \faceprog\com\CalLi840.pas
copy \faceprog\com\ColBtn.pas
copy \faceprog\com\comd.pas
copy \faceprog\com\comdis.pas
copy \faceprog\com\comin.pas
copy \faceprog\com\comlog.pas
copy \faceprog\com\comp.pas
copy \faceprog\com\Compare.pas
copy \faceprog\com\coms.pas
copy \faceprog\com\comu.pas
copy \faceprog\com\Connect.pas
copy \FaceProg\Delphi6\Projects\JN\crt32.pas
copy \faceprog\com\DataComm.pas
copy \faceprog\com\debuglog.pas
copy \faceprog\com\Ephem.pas
copy \faceprog\com\EventLog.pas
copy \faceprog\com\ExitSeq.pas
copy \faceprog\com\faced.pas
copy \faceprog\com\FatalErr.pas
copy \faceprog\com\FestoCI.pas
copy \faceprog\com\Globals.pas
copy \faceprog\com\gra.pas
copy \FaceProg\Delphi6\Projects\JN\graph32.pas
copy \faceprog\com\H2OVapor.pas
copy \faceprog\com\Heart.pas
copy \faceprog\com\IPServ.pas
copy \faceprog\com\LblForm.pas
copy \faceprog\com\LGSelect.pas
copy \faceprog\com\LGSetup.pas
copy \faceprog\com\licor.pas
copy \faceprog\com\LineGraf.pas
copy \faceprog\com\LineIn.pas
copy \faceprog\com\Main.pas
copy \faceprog\com\MPSample.pas
copy \faceprog\com\musca.pas
copy \Programs\NativeXML\unzipped\NativeXML404\nativexml\NativeXML.pas
copy \faceprog\com\netinfo.pas
copy \faceprog\com\NetLog.pas
copy \faceprog\com\optomux.pas
copy \faceprog\com\RingBar.pas
copy \faceprog\com\riv.pas
copy \faceprog\com\RVSetup.pas
copy \Programs\NativeXML\unzipped\NativeXML404\general\sdDebug.pas
copy \Programs\NativeXML\unzipped\NativeXML404\general\sdStreams.pas
copy \Programs\NativeXML\unzipped\NativeXML404\general\sdStringTable.pas
copy \faceprog\com\Serial.pas
copy \faceprog\com\Services.pas
copy \faceprog\com\Socket.pas
copy \faceprog\com\Sol.pas
copy \faceprog\com\Status.pas
copy \faceprog\com\tei49c.pas
copy \faceprog\com\Template.pas
copy \faceprog\com\UtilObjs.pas
copy \faceprog\com\Watchdog.pas
copy \Programs\DeviceIO\WinIOv20\WinIOTst\WinIO.pas
copy \faceprog\com\TEMPLATE.DFM
copy \faceprog\com\LblForm.dfm
copy \faceprog\com\DataComm.dfm
copy \faceprog\com\CalLi840.dfm
copy \faceprog\com\CalibMan.dfm
copy \faceprog\com\Watchdog.dfm
copy \faceprog\com\LineGraf.dfm
copy \faceprog\com\LGSetup.dfm
copy \faceprog\com\COMPARE.dfm
copy \faceprog\com\EPHEM.DFM
copy \faceprog\com\H2OVAPOR.DFM
copy \faceprog\com\Status.dfm
copy \faceprog\com\MPSample.dfm
copy \faceprog\com\LGSelect.dfm
copy \faceprog\com\Alarms.dfm
copy \faceprog\com\CalibAut.dfm
copy \faceprog\com\Main.dfm
